version: "3.8"

x-arguments: &arguments
  GID: ${GID}
  UID: ${UID}
  XDEBUG_HOST: ${XDEBUG_HOST}
  XDEBUG_PORT: ${XDEBUG_PORT}

services:
  fpm:
    container_name: ${PROJECT_NAME}_fpm
    build:
      args:
        <<: *arguments
      context: .
      dockerfile: "docker/fpm/Dockerfile"
    volumes:
      - "./codebase:/project/src/codebase"
      - "./data:/project/src/data"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - backend

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    image: nginx:1.24
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=lo-exc
      - POSTGRES_USER=lo-exc
      - POSTGRES_DB=lo-exc
    networks:
      - backend

  postgres_test:
    image: postgres:14-alpine
    ports:
      - ${TEST_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=lo-exc
      - POSTGRES_USER=lo-exc
      - POSTGRES_DB=lo-exc
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
